// AUTO-GENERATED — do not edit. Run `yarn generate:help` to regenerate.
export type HelpKey =
  | "admin-overview"
  | "almanac-overview"
  | "aperture-overview"
  | "atelier-overview"
  | "bazaar-overview"
  | "chat-overview"
  | "clients-overview"
  | "community-hub-overview"
  | "console-overview"
  | "dashboard-overview"
  | "demos-overview"
  | "dispatch-overview"
  | "feedback-overview"
  | "groups-overview"
  | "help-overview"
  | "initiatives-overview"
  | "living-books-overview"
  | "member-overview"
  | "mobile-overview"
  | "notifications-overview"
  | "projects-overview"
  | "puddlejump-overview"
  | "stackroom-overview"
  | "workbench-overview"
  | "writing-overview";
