// Tenant palettes for Group Presence Tier 2+.
// Distinct from visitor platform themes (packages/ui-tokens/src/themes.ts).
// Stored per group as presentation.palette_id; selected by admin, not visitor.
// All accents clear 4.5:1 against their bg.

import type { ThemeDefinition } from "@mixtape/core";

export const tenantPalettes: ThemeDefinition[] = [
  {
    id: "quarto",
    name: "Quarto",
    light: {
      bg: "#F6F7F8",
      bgSecondary: "#EEF0F2",
      surface: "#FFFFFF",
      accent: "#2F4E86",
      text: "#171C22",
      textSecondary: "#4C5661",
      border: "#DCE0E5",
    },
    dark: {
      bg: "#101418",
      bgSecondary: "#161B21",
      surface: "#191F26",
      accent: "#8FB2E8",
      text: "#EDF0F3",
      textSecondary: "#A3AEB9",
      border: "#2A323B",
    },
    lightHighContrast: {
      bg: "#FFFFFF",
      bgSecondary: "#F7F7F7",
      surface: "#F2F2F2",
      accent: "#1B3566",
      text: "#000000",
      textSecondary: "#1A1A1A",
      border: "#5C5C5C",
    },
    darkHighContrast: {
      bg: "#000000",
      bgSecondary: "#0D0D0D",
      surface: "#141414",
      accent: "#B9D4FF",
      text: "#FFFFFF",
      textSecondary: "#E6E6E6",
      border: "#C9C9C9",
    },
  },
  {
    id: "foolscap",
    name: "Foolscap",
    light: {
      bg: "#FAF6EE",
      bgSecondary: "#F2EBDF",
      surface: "#FFFDF8",
      accent: "#7C2B23",
      text: "#241E1A",
      textSecondary: "#5C5147",
      border: "#E3D9C8",
    },
    dark: {
      bg: "#17140F",
      bgSecondary: "#1D1914",
      surface: "#221D17",
      accent: "#D98C7A",
      text: "#F1EADE",
      textSecondary: "#B3A695",
      border: "#332C24",
    },
    lightHighContrast: {
      bg: "#FFFFFF",
      bgSecondary: "#FAF8F3",
      surface: "#F5F1E9",
      accent: "#5B1710",
      text: "#000000",
      textSecondary: "#1A1A1A",
      border: "#5C5347",
    },
    darkHighContrast: {
      bg: "#000000",
      bgSecondary: "#0F0D0B",
      surface: "#171310",
      accent: "#FFC2B0",
      text: "#FFFFFF",
      textSecondary: "#EDE6DA",
      border: "#CFC6B8",
    },
  },
  {
    id: "pigment",
    name: "Pigment",
    light: {
      bg: "#FFFFFF",
      bgSecondary: "#F4F4F4",
      surface: "#FFFFFF",
      accent: "#D6350F",
      text: "#0B0B0B",
      textSecondary: "#55555A",
      border: "#E6E6E6",
    },
    dark: {
      bg: "#0A0A0A",
      bgSecondary: "#121212",
      surface: "#141414",
      accent: "#FF6A3D",
      text: "#FAFAFA",
      textSecondary: "#A8A8AC",
      border: "#262626",
    },
    lightHighContrast: {
      bg: "#FFFFFF",
      bgSecondary: "#F5F5F5",
      surface: "#F0F0F0",
      accent: "#A32300",
      text: "#000000",
      textSecondary: "#171717",
      border: "#565656",
    },
    darkHighContrast: {
      bg: "#000000",
      bgSecondary: "#0D0D0D",
      surface: "#121212",
      accent: "#FF9E7A",
      text: "#FFFFFF",
      textSecondary: "#EBEBEB",
      border: "#CCCCCC",
    },
  },
  {
    id: "common",
    name: "Common",
    light: {
      bg: "#F4F7F3",
      bgSecondary: "#E9EFE7",
      surface: "#FFFFFF",
      accent: "#1F6B5B",
      text: "#16211D",
      textSecondary: "#4A5A54",
      border: "#D6E0D6",
    },
    dark: {
      bg: "#0E1512",
      bgSecondary: "#131C18",
      surface: "#17211D",
      accent: "#74C9AF",
      text: "#E9F1EC",
      textSecondary: "#9DB0A8",
      border: "#26332D",
    },
    lightHighContrast: {
      bg: "#FFFFFF",
      bgSecondary: "#F5F8F5",
      surface: "#F1F5F1",
      accent: "#0E4A3D",
      text: "#000000",
      textSecondary: "#1A1A1A",
      border: "#5A625B",
    },
    darkHighContrast: {
      bg: "#000000",
      bgSecondary: "#0A0F0C",
      surface: "#101614",
      accent: "#9EF0D6",
      text: "#FFFFFF",
      textSecondary: "#E8F0EB",
      border: "#C7D2CB",
    },
  },
];
